spring.datasource:
  url: jdbc:postgresql://localhost/postgres
  username: postgres
  password: scrapsafe
  driver-class-name: org.postgresql.Driver

camunda:
  bpm:
    job-execution:
      core-pool-size: 10
    authorization.enabled: true
    webapp:
        csrf: 
            target-origin: https://herokumunda.herokuapp.com/
            enable-secure-cookie: true
            enable-same-site-cookie: true
            same-site-cookie-option: strict
        
        